//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//

package com.sldeditor.common.xml.envvar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EnvVarTypeList" type="{}XMLEnvVarTypeList"/&gt;
 *         &lt;element name="BuiltInEnvVarList" type="{}XMLBuiltInEnvVarList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "",
        propOrder = {"envVarTypeList", "builtInEnvVarList"})
@XmlRootElement(name = "EnvironmentVariables")
public class EnvironmentVariables {

    @XmlElement(name = "EnvVarTypeList", required = true)
    protected XMLEnvVarTypeList envVarTypeList;

    @XmlElement(name = "BuiltInEnvVarList", required = true)
    protected XMLBuiltInEnvVarList builtInEnvVarList;

    /**
     * Gets the value of the envVarTypeList property.
     *
     * @return possible object is {@link XMLEnvVarTypeList }
     */
    public XMLEnvVarTypeList getEnvVarTypeList() {
        return envVarTypeList;
    }

    /**
     * Sets the value of the envVarTypeList property.
     *
     * @param value allowed object is {@link XMLEnvVarTypeList }
     */
    public void setEnvVarTypeList(XMLEnvVarTypeList value) {
        this.envVarTypeList = value;
    }

    /**
     * Gets the value of the builtInEnvVarList property.
     *
     * @return possible object is {@link XMLBuiltInEnvVarList }
     */
    public XMLBuiltInEnvVarList getBuiltInEnvVarList() {
        return builtInEnvVarList;
    }

    /**
     * Sets the value of the builtInEnvVarList property.
     *
     * @param value allowed object is {@link XMLBuiltInEnvVarList }
     */
    public void setBuiltInEnvVarList(XMLBuiltInEnvVarList value) {
        this.builtInEnvVarList = value;
    }
}
