//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//


package com.sldeditor.common.xml.loadextension;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtensionTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExtensionTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FILE_HANDLER"/&gt;
 *     &lt;enumeration value="DATA_FLAVOUR"/&gt;
 *     &lt;enumeration value="TOOL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ExtensionTypeEnum")
@XmlEnum
public enum ExtensionTypeEnum {

    FILE_HANDLER,
    DATA_FLAVOUR,
    TOOL;

    public String value() {
        return name();
    }

    public static ExtensionTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
