//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//

package com.sldeditor.common.xml.ui;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for GroupIdEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p>
 *
 * <pre>
 * &lt;simpleType name="GroupIdEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="STANDARD"/&gt;
 *     &lt;enumeration value="GENERAL"/&gt;
 *     &lt;enumeration value="ANCHORPOINT"/&gt;
 *     &lt;enumeration value="DISPLACEMENT"/&gt;
 *     &lt;enumeration value="ROTATION"/&gt;
 *     &lt;enumeration value="SCALE"/&gt;
 *     &lt;enumeration value="FILL"/&gt;
 *     &lt;enumeration value="FILLSYMBOL"/&gt;
 *     &lt;enumeration value="STROKE"/&gt;
 *     &lt;enumeration value="STROKESYMBOL"/&gt;
 *     &lt;enumeration value="STROKEANCHORPOINT"/&gt;
 *     &lt;enumeration value="STROKEDISPLACEMENT"/&gt;
 *     &lt;enumeration value="FILLCOLOUR"/&gt;
 *     &lt;enumeration value="STROKECOLOUR"/&gt;
 *     &lt;enumeration value="FONT"/&gt;
 *     &lt;enumeration value="HALO"/&gt;
 *     &lt;enumeration value="PLACEMENT"/&gt;
 *     &lt;enumeration value="POINTPLACEMENT"/&gt;
 *     &lt;enumeration value="LINEPLACEMENT"/&gt;
 *     &lt;enumeration value="HALO"/&gt;
 *     &lt;enumeration value="VO_LABELLING"/&gt;
 *     &lt;enumeration value="VO_LABELLING_UNDERLINE"/&gt;
 *     &lt;enumeration value="VO_RANDOMFILL"/&gt;
 *     &lt;enumeration value="VO_POINT_RANDOMFILL"/&gt;
 *     &lt;enumeration value="VO_POLYGON_RANDOMFILL"/&gt;
 *     &lt;enumeration value="VO_RASTER_NORMALIZE_RED"/&gt;
 *     &lt;enumeration value="VO_RASTER_NORMALIZE_GREEN"/&gt;
 *     &lt;enumeration value="VO_RASTER_NORMALIZE_BLUE"/&gt;
 *     &lt;enumeration value="VO_RASTER_NORMALIZE_GREY"/&gt;
 *     &lt;enumeration value="VO_RASTER_NORMALIZE_OVERALL"/&gt;
 *     &lt;enumeration value="RASTER"/&gt;
 *     &lt;enumeration value="RASTER_CONTRAST"/&gt;
 *     &lt;enumeration value="RASTER_OVERALL_CONTRAST_METHOD"/&gt;
 *     &lt;enumeration value="RASTER_OVERALL_CONTRAST_METHOD_NONE"/&gt;
 *     &lt;enumeration value="RASTER_OVERALL_CONTRAST_METHOD_EXPONENTIAL"/&gt;
 *     &lt;enumeration value="RASTER_OVERALL_CONTRAST_METHOD_HISTOGRAM"/&gt;
 *     &lt;enumeration value="RASTER_OVERALL_CONTRAST_METHOD_LOGARITHMIC"/&gt;
 *     &lt;enumeration value="RASTER_OVERALL_CONTRAST_METHOD_NORMALIZE"/&gt;
 *     &lt;enumeration value="RASTER_OVERALL_CONTRAST_METHOD_NORMALIZE_GROUP"/&gt;
 *     &lt;enumeration value="RASTER_CHANNELSELECTION"/&gt;
 *     &lt;enumeration value="RASTER_SHADEDRELIEF"/&gt;
 *     &lt;enumeration value="RASTER_OVERLAP"/&gt;
 *     &lt;enumeration value="RASTER_COLOURMAP"/&gt;
 *     &lt;enumeration value="RASTER_CHANNELSELECTION"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_OPTION"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_RED"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_RED_CONTRAST"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD_NONE"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD_EXPONENTIAL"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD_HISTOGRAM"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD_LOGARITHMIC"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD_NORMALIZE"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD_NORMALIZE_GROUP"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREEN"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREEN_CONTRAST"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD_NONE"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD_EXPONENTIAL"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD_HISTOGRAM"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD_LOGARITHMIC"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD_NORMALIZE"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD_NORMALIZE_GROUP"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_BLUE"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_BLUE_CONTRAST"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD_NONE"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD_EXPONENTIAL"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD_HISTOGRAM"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD_LOGARITHMIC"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD_NORMALIZE"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD_NORMALIZE_GROUP"/&gt;
 *     &lt;enumeration value="RASTER_GREY_CHANNEL_OPTION"/&gt;
 *     &lt;enumeration value="RASTER_GREY_CHANNEL"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREY_CONTRAST"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD_NONE"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD_EXPONENTIAL"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD_HISTOGRAM"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD_LOGARITHMIC"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD_NORMALIZE"/&gt;
 *     &lt;enumeration value="RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD_NORMALIZE_GROUP"/&gt;
 *     &lt;enumeration value="REMOTE_OWS"/&gt;
 *     &lt;enumeration value="REMOTE_OWS_OPTION"/&gt;
 *     &lt;enumeration value="FEATURE_TYPE_CONSTRAINTS"/&gt;
 *     &lt;enumeration value="INLINE_FEATURE"/&gt;
 *     &lt;enumeration value="INLINE_FEATURE_OPTION"/&gt;
 *     &lt;enumeration value="USER_LAYER_SOURCE"/&gt;
 *     &lt;enumeration value="VO_TEXT_LABEL"/&gt;
 *     &lt;enumeration value="VO_TEXT_LABEL_UNDERLINE"/&gt;
 *     &lt;enumeration value="VO_TEXTSYMBOLIZER_2"/&gt;
 *     &lt;enumeration value="VO_TEXTSYMBOLIZER_2_GRAPHIC"/&gt;
 *     &lt;enumeration value="VO_TEXTSYMBOLIZER_2_FILL"/&gt;
 *     &lt;enumeration value="VO_TEXTSYMBOLIZER_2_STROKE"/&gt;
 *     &lt;enumeration value="VO_TEXTSYMBOLIZER_2_OTHERTEXT"/&gt;
 *     &lt;enumeration value="VO_TEXT_SPACING"/&gt;
 *     &lt;enumeration value="VO_FTS"/&gt;
 *     &lt;enumeration value="VO_FTS_COMPOSITE"/&gt;
 *     &lt;enumeration value="VO_FTS_COMPOSITE_BASE"/&gt;
 *     &lt;enumeration value="VO_FTS_RULE_EVALUATION"/&gt;
 *     &lt;enumeration value="VO_FTS_SORTBY_MULTIOPTION"/&gt;
 *     &lt;enumeration value="VO_FTS_SORTBY_MULTIOPTION_SORTBY_OPTION"/&gt;
 *     &lt;enumeration value="VO_FTS_SORTBY_MULTIOPTION_SORTBY"/&gt;
 *     &lt;enumeration value="VO_FTS_SORTBY_MULTIOPTION_SORTBY_GROUP"/&gt;
 *     &lt;enumeration value="VO_FTS_SORTBY_MULTIOPTION_SORTBY_GROUP_OPTION"/&gt;
 *     &lt;enumeration value="VO_RASTER_RED_NAME_EXPRESSION"/&gt;
 *     &lt;enumeration value="VO_RASTER_RED_NAME_STRING"/&gt;
 *     &lt;enumeration value="VO_RASTER_GREEN_NAME_EXPRESSION"/&gt;
 *     &lt;enumeration value="VO_RASTER_GREEN_NAME_STRING"/&gt;
 *     &lt;enumeration value="VO_RASTER_BLUE_NAME_EXPRESSION"/&gt;
 *     &lt;enumeration value="VO_RASTER_BLUE_NAME_STRING"/&gt;
 *     &lt;enumeration value="VO_RASTER_GREY_NAME_EXPRESSION"/&gt;
 *     &lt;enumeration value="VO_RASTER_GREY_NAME_STRING"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "GroupIdEnum")
@XmlEnum
public enum GroupIdEnum {
    UNKNOWN,
    STANDARD,
    GENERAL,
    ANCHORPOINT,
    DISPLACEMENT,
    ROTATION,
    SCALE,
    FILL,
    FILLSYMBOL,
    STROKE,
    STROKESYMBOL,
    STROKEANCHORPOINT,
    STROKEDISPLACEMENT,
    FILLCOLOUR,
    STROKECOLOUR,
    FONT,
    HALO,
    PLACEMENT,
    POINTPLACEMENT,
    LINEPLACEMENT,
    VO_LABELLING,
    VO_LABELLING_UNDERLINE,
    VO_RANDOMFILL,
    VO_POINT_RANDOMFILL,
    VO_POLYGON_RANDOMFILL,
    VO_RASTER_NORMALIZE_RED,
    VO_RASTER_NORMALIZE_GREEN,
    VO_RASTER_NORMALIZE_BLUE,
    VO_RASTER_NORMALIZE_GREY,
    VO_RASTER_NORMALIZE_OVERALL,
    RASTER,
    RASTER_CONTRAST,
    RASTER_OVERALL_CONTRAST_METHOD,
    RASTER_OVERALL_CONTRAST_METHOD_NONE,
    RASTER_OVERALL_CONTRAST_METHOD_EXPONENTIAL,
    RASTER_OVERALL_CONTRAST_METHOD_HISTOGRAM,
    RASTER_OVERALL_CONTRAST_METHOD_LOGARITHMIC,
    RASTER_OVERALL_CONTRAST_METHOD_NORMALIZE,
    RASTER_OVERALL_CONTRAST_METHOD_NORMALIZE_GROUP,
    RASTER_CHANNELSELECTION,
    RASTER_SHADEDRELIEF,
    RASTER_OVERLAP,
    RASTER_COLOURMAP,
    RASTER_RGB_CHANNEL_OPTION,
    RASTER_RGB_CHANNEL_RED,
    RASTER_RGB_CHANNEL_RED_CONTRAST,
    RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD,
    RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD_NONE,
    RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD_EXPONENTIAL,
    RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD_HISTOGRAM,
    RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD_LOGARITHMIC,
    RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD_NORMALIZE,
    RASTER_RGB_CHANNEL_RED_CONTRAST_METHOD_NORMALIZE_GROUP,
    RASTER_RGB_CHANNEL_GREEN,
    RASTER_RGB_CHANNEL_GREEN_CONTRAST,
    RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD,
    RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD_NONE,
    RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD_EXPONENTIAL,
    RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD_HISTOGRAM,
    RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD_LOGARITHMIC,
    RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD_NORMALIZE,
    RASTER_RGB_CHANNEL_GREEN_CONTRAST_METHOD_NORMALIZE_GROUP,
    RASTER_RGB_CHANNEL_BLUE,
    RASTER_RGB_CHANNEL_BLUE_CONTRAST,
    RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD,
    RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD_NONE,
    RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD_EXPONENTIAL,
    RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD_HISTOGRAM,
    RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD_LOGARITHMIC,
    RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD_NORMALIZE,
    RASTER_RGB_CHANNEL_BLUE_CONTRAST_METHOD_NORMALIZE_GROUP,
    RASTER_GREY_CHANNEL_OPTION,
    RASTER_GREY_CHANNEL,
    RASTER_RGB_CHANNEL_GREY_CONTRAST,
    RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD,
    RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD_NONE,
    RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD_EXPONENTIAL,
    RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD_HISTOGRAM,
    RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD_LOGARITHMIC,
    RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD_NORMALIZE,
    RASTER_RGB_CHANNEL_GREY_CONTRAST_METHOD_NORMALIZE_GROUP,
    REMOTE_OWS,
    REMOTE_OWS_OPTION,
    FEATURE_TYPE_CONSTRAINTS,
    INLINE_FEATURE,
    INLINE_FEATURE_OPTION,
    USER_LAYER_SOURCE,
    VO_TEXT_LABEL,
    VO_TEXT_LABEL_UNDERLINE,
    VO_TEXTSYMBOLIZER_2,
    VO_TEXTSYMBOLIZER_2_GRAPHIC,
    VO_TEXTSYMBOLIZER_2_FILL,
    VO_TEXTSYMBOLIZER_2_STROKE,
    VO_TEXTSYMBOLIZER_2_OTHERTEXT,
    VO_TEXT_SPACING,
    VO_FTS,
    VO_FTS_COMPOSITE,
    VO_FTS_COMPOSITE_BASE,
    VO_FTS_RULE_EVALUATION,
    VO_FTS_SORTBY_MULTIOPTION,
    VO_FTS_SORTBY_MULTIOPTION_SORTBY_OPTION,
    VO_FTS_SORTBY_MULTIOPTION_SORTBY,
    VO_FTS_SORTBY_MULTIOPTION_SORTBY_GROUP,
    VO_FTS_SORTBY_MULTIOPTION_SORTBY_GROUP_OPTION,
    VO_RASTER_RED_NAME_EXPRESSION,
    VO_RASTER_RED_NAME_STRING,
    VO_RASTER_GREEN_NAME_EXPRESSION,
    VO_RASTER_GREEN_NAME_STRING,
    VO_RASTER_BLUE_NAME_EXPRESSION,
    VO_RASTER_BLUE_NAME_STRING,
    VO_RASTER_GREY_NAME_EXPRESSION,
    VO_RASTER_GREY_NAME_STRING;

    public String value() {
        return name();
    }

    public static GroupIdEnum fromValue(String v) {
        return valueOf(v);
    }
}
