//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//


package com.sldeditor.common.xml.ui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                     Describes how panel is made up
 *                 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FieldConfigEnum" type="{}XMLFieldConfigEnum"/>
 *       &lt;/sequence>
 *       &lt;attribute name="localisation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fieldConfigEnum"
})
@XmlRootElement(name = "MapUnits")
public class MapUnits {

    @XmlElement(name = "FieldConfigEnum", required = true)
    protected XMLFieldConfigEnum fieldConfigEnum;
    @XmlAttribute
    protected String localisation;

    /**
     * Gets the value of the fieldConfigEnum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLFieldConfigEnum }
     *     
     */
    public XMLFieldConfigEnum getFieldConfigEnum() {
        return fieldConfigEnum;
    }

    /**
     * Sets the value of the fieldConfigEnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLFieldConfigEnum }
     *     
     */
    public void setFieldConfigEnum(XMLFieldConfigEnum value) {
        this.fieldConfigEnum = value;
    }

    /**
     * Gets the value of the localisation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalisation() {
        return localisation;
    }

    /**
     * Sets the value of the localisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalisation(String value) {
        this.localisation = value;
    }

}
