//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//


package com.sldeditor.common.xml.ui;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sldeditor.common.xml.ui package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sldeditor.common.xml.ui
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLFieldConfigEnumValue }
     * 
     */
    public XMLFieldConfigEnumValue createXMLFieldConfigEnumValue() {
        return new XMLFieldConfigEnumValue();
    }

    /**
     * Create an instance of {@link ColourRampPresets }
     * 
     */
    public ColourRampPresets createColourRampPresets() {
        return new ColourRampPresets();
    }

    /**
     * Create an instance of {@link XMLTwoColourRampList }
     * 
     */
    public XMLTwoColourRampList createXMLTwoColourRampList() {
        return new XMLTwoColourRampList();
    }

    /**
     * Create an instance of {@link PanelConfig }
     * 
     */
    public PanelConfig createPanelConfig() {
        return new PanelConfig();
    }

    /**
     * Create an instance of {@link XMLGroupConfig }
     * 
     */
    public XMLGroupConfig createXMLGroupConfig() {
        return new XMLGroupConfig();
    }

    /**
     * Create an instance of {@link XMLMultiOptionGroup }
     * 
     */
    public XMLMultiOptionGroup createXMLMultiOptionGroup() {
        return new XMLMultiOptionGroup();
    }

    /**
     * Create an instance of {@link XMLSymbolTypeConfig }
     * 
     */
    public XMLSymbolTypeConfig createXMLSymbolTypeConfig() {
        return new XMLSymbolTypeConfig();
    }

    /**
     * Create an instance of {@link XMLPanelDetails }
     * 
     */
    public XMLPanelDetails createXMLPanelDetails() {
        return new XMLPanelDetails();
    }

    /**
     * Create an instance of {@link SLDXPath }
     * 
     */
    public SLDXPath createSLDXPath() {
        return new SLDXPath();
    }

    /**
     * Create an instance of {@link XMLTestSection }
     * 
     */
    public XMLTestSection createXMLTestSection() {
        return new XMLTestSection();
    }

    /**
     * Create an instance of {@link SldEditorTest }
     * 
     */
    public SldEditorTest createSldEditorTest() {
        return new SldEditorTest();
    }

    /**
     * Create an instance of {@link XMLVendorOption }
     * 
     */
    public XMLVendorOption createXMLVendorOption() {
        return new XMLVendorOption();
    }

    /**
     * Create an instance of {@link XMLPanelTest }
     * 
     */
    public XMLPanelTest createXMLPanelTest() {
        return new XMLPanelTest();
    }

    /**
     * Create an instance of {@link XMLTwoColourRamp }
     * 
     */
    public XMLTwoColourRamp createXMLTwoColourRamp() {
        return new XMLTwoColourRamp();
    }

    /**
     * Create an instance of {@link XMLGroupConfigData }
     * 
     */
    public XMLGroupConfigData createXMLGroupConfigData() {
        return new XMLGroupConfigData();
    }

    /**
     * Create an instance of {@link XMLFieldConfigSymbolType }
     * 
     */
    public XMLFieldConfigSymbolType createXMLFieldConfigSymbolType() {
        return new XMLFieldConfigSymbolType();
    }

    /**
     * Create an instance of {@link XMLFieldConfigDouble }
     * 
     */
    public XMLFieldConfigDouble createXMLFieldConfigDouble() {
        return new XMLFieldConfigDouble();
    }

    /**
     * Create an instance of {@link XMLFieldConfigColourMap }
     * 
     */
    public XMLFieldConfigColourMap createXMLFieldConfigColourMap() {
        return new XMLFieldConfigColourMap();
    }

    /**
     * Create an instance of {@link XMLFieldConfigTransformation }
     * 
     */
    public XMLFieldConfigTransformation createXMLFieldConfigTransformation() {
        return new XMLFieldConfigTransformation();
    }

    /**
     * Create an instance of {@link XMLFieldConfigInlineFeature }
     * 
     */
    public XMLFieldConfigInlineFeature createXMLFieldConfigInlineFeature() {
        return new XMLFieldConfigInlineFeature();
    }

    /**
     * Create an instance of {@link XMLFieldConfigFeatureTypeConstraint }
     * 
     */
    public XMLFieldConfigFeatureTypeConstraint createXMLFieldConfigFeatureTypeConstraint() {
        return new XMLFieldConfigFeatureTypeConstraint();
    }

    /**
     * Create an instance of {@link XMLFieldConfigEnum }
     * 
     */
    public XMLFieldConfigEnum createXMLFieldConfigEnum() {
        return new XMLFieldConfigEnum();
    }

    /**
     * Create an instance of {@link XMLFieldConfigEnumValueList }
     * 
     */
    public XMLFieldConfigEnumValueList createXMLFieldConfigEnumValueList() {
        return new XMLFieldConfigEnumValueList();
    }

    /**
     * Create an instance of {@link XMLFieldConfigEnumValueItem }
     * 
     */
    public XMLFieldConfigEnumValueItem createXMLFieldConfigEnumValueItem() {
        return new XMLFieldConfigEnumValueItem();
    }

    /**
     * Create an instance of {@link XMLFieldConfigEnumValueField }
     * 
     */
    public XMLFieldConfigEnumValueField createXMLFieldConfigEnumValueField() {
        return new XMLFieldConfigEnumValueField();
    }

    /**
     * Create an instance of {@link XMLFieldConfigString }
     * 
     */
    public XMLFieldConfigString createXMLFieldConfigString() {
        return new XMLFieldConfigString();
    }

    /**
     * Create an instance of {@link XMLFieldConfigGeometryField }
     * 
     */
    public XMLFieldConfigGeometryField createXMLFieldConfigGeometryField() {
        return new XMLFieldConfigGeometryField();
    }

    /**
     * Create an instance of {@link XMLFieldConfigFont }
     * 
     */
    public XMLFieldConfigFont createXMLFieldConfigFont() {
        return new XMLFieldConfigFont();
    }

    /**
     * Create an instance of {@link XMLFieldConfigFontPreview }
     * 
     */
    public XMLFieldConfigFontPreview createXMLFieldConfigFontPreview() {
        return new XMLFieldConfigFontPreview();
    }

    /**
     * Create an instance of {@link XMLFieldConfigGeometry }
     * 
     */
    public XMLFieldConfigGeometry createXMLFieldConfigGeometry() {
        return new XMLFieldConfigGeometry();
    }

    /**
     * Create an instance of {@link XMLFieldConfigSlider }
     * 
     */
    public XMLFieldConfigSlider createXMLFieldConfigSlider() {
        return new XMLFieldConfigSlider();
    }

    /**
     * Create an instance of {@link XMLFieldConfigColour }
     * 
     */
    public XMLFieldConfigColour createXMLFieldConfigColour() {
        return new XMLFieldConfigColour();
    }

    /**
     * Create an instance of {@link XMLFieldConfigBoolean }
     * 
     */
    public XMLFieldConfigBoolean createXMLFieldConfigBoolean() {
        return new XMLFieldConfigBoolean();
    }

    /**
     * Create an instance of {@link XMLFieldConfigInteger }
     * 
     */
    public XMLFieldConfigInteger createXMLFieldConfigInteger() {
        return new XMLFieldConfigInteger();
    }

    /**
     * Create an instance of {@link XMLFieldConfigData }
     * 
     */
    public XMLFieldConfigData createXMLFieldConfigData() {
        return new XMLFieldConfigData();
    }

    /**
     * Create an instance of {@link XMLOptionGroup }
     * 
     */
    public XMLOptionGroup createXMLOptionGroup() {
        return new XMLOptionGroup();
    }

    /**
     * Create an instance of {@link XMLTestSectionField }
     * 
     */
    public XMLTestSectionField createXMLTestSectionField() {
        return new XMLTestSectionField();
    }

    /**
     * Create an instance of {@link XMLSetup }
     * 
     */
    public XMLSetup createXMLSetup() {
        return new XMLSetup();
    }

    /**
     * Create an instance of {@link XMLIndex }
     * 
     */
    public XMLIndex createXMLIndex() {
        return new XMLIndex();
    }

    /**
     * Create an instance of {@link XMLFieldTest }
     * 
     */
    public XMLFieldTest createXMLFieldTest() {
        return new XMLFieldTest();
    }

    /**
     * Create an instance of {@link XMLSetMultiOptionGroup }
     * 
     */
    public XMLSetMultiOptionGroup createXMLSetMultiOptionGroup() {
        return new XMLSetMultiOptionGroup();
    }

    /**
     * Create an instance of {@link XMLSetGroup }
     * 
     */
    public XMLSetGroup createXMLSetGroup() {
        return new XMLSetGroup();
    }

    /**
     * Create an instance of {@link XMLFieldBase }
     * 
     */
    public XMLFieldBase createXMLFieldBase() {
        return new XMLFieldBase();
    }

    /**
     * Create an instance of {@link XMLFieldDisabled }
     * 
     */
    public XMLFieldDisabled createXMLFieldDisabled() {
        return new XMLFieldDisabled();
    }

    /**
     * Create an instance of {@link XMLFieldLiteralString }
     * 
     */
    public XMLFieldLiteralString createXMLFieldLiteralString() {
        return new XMLFieldLiteralString();
    }

    /**
     * Create an instance of {@link XMLSetFieldLiteralString }
     * 
     */
    public XMLSetFieldLiteralString createXMLSetFieldLiteralString() {
        return new XMLSetFieldLiteralStringEx();
    }

    /**
     * Create an instance of {@link XMLFieldLiteralInt }
     * 
     */
    public XMLFieldLiteralInt createXMLFieldLiteralInt() {
        return new XMLFieldLiteralInt();
    }

    /**
     * Create an instance of {@link XMLSetFieldLiteralInt }
     * 
     */
    public XMLSetFieldLiteralInt createXMLSetFieldLiteralInt() {
        return new XMLSetFieldLiteralIntEx();
    }

    /**
     * Create an instance of {@link XMLFieldLiteralDouble }
     * 
     */
    public XMLFieldLiteralDouble createXMLFieldLiteralDouble() {
        return new XMLFieldLiteralDouble();
    }

    /**
     * Create an instance of {@link XMLSetFieldLiteralDouble }
     * 
     */
    public XMLSetFieldLiteralDouble createXMLSetFieldLiteralDouble() {
        return new XMLSetFieldLiteralDoubleEx();
    }

    /**
     * Create an instance of {@link XMLFieldLiteralBoolean }
     * 
     */
    public XMLFieldLiteralBoolean createXMLFieldLiteralBoolean() {
        return new XMLFieldLiteralBoolean();
    }

    /**
     * Create an instance of {@link XMLSetFieldLiteralBoolean }
     * 
     */
    public XMLSetFieldLiteralBoolean createXMLSetFieldLiteralBoolean() {
        return new XMLSetFieldLiteralBooleanEx();
    }

    /**
     * Create an instance of {@link XMLFieldLiteralBase }
     * 
     */
    public XMLFieldLiteralBase createXMLFieldLiteralBase() {
        return new XMLFieldLiteralBase();
    }

    /**
     * Create an instance of {@link XMLSetFieldLiteralBase }
     * 
     */
    public XMLSetFieldLiteralBase createXMLSetFieldLiteralBase() {
        return new XMLSetFieldLiteralBase();
    }

    /**
     * Create an instance of {@link XMLFieldExpression }
     * 
     */
    public XMLFieldExpression createXMLFieldExpression() {
        return new XMLFieldExpression();
    }

    /**
     * Create an instance of {@link XMLSetFieldExpression }
     * 
     */
    public XMLSetFieldExpression createXMLSetFieldExpression() {
        return new XMLSetFieldExpressionEx();
    }

    /**
     * Create an instance of {@link XMLFieldAttribute }
     * 
     */
    public XMLFieldAttribute createXMLFieldAttribute() {
        return new XMLFieldAttribute();
    }

    /**
     * Create an instance of {@link XMLSetFieldAttribute }
     * 
     */
    public XMLSetFieldAttribute createXMLSetFieldAttribute() {
        return new XMLSetFieldAttributeEx();
    }

    /**
     * Create an instance of {@link XMLFieldConfigEnumValue.FieldList }
     * 
     */
    public XMLFieldConfigEnumValue.FieldList createXMLFieldConfigEnumValueFieldList() {
        return new XMLFieldConfigEnumValue.FieldList();
    }

}
