//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//


package com.sldeditor.common.xml.ui;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SelectedTreeItemEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SelectedTreeItemEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UNKNOWN"/>
 *     &lt;enumeration value="SLD"/>
 *     &lt;enumeration value="LAYER"/>
 *     &lt;enumeration value="STYLE"/>
 *     &lt;enumeration value="FEATURETYPESTYLE"/>
 *     &lt;enumeration value="RULE"/>
 *     &lt;enumeration value="POINT_SYMBOLIZER"/>
 *     &lt;enumeration value="LINE_SYMBOLIZER"/>
 *     &lt;enumeration value="POLYGON_SYMBOLIZER"/>
 *     &lt;enumeration value="TEXT_SYMBOLIZER"/>
 *     &lt;enumeration value="RASTER_SYMBOLIZER"/>
 *     &lt;enumeration value="POINT_FILL"/>
 *     &lt;enumeration value="POLYGON_FILL"/>
 *     &lt;enumeration value="STROKE"/>
 *     &lt;enumeration value="STROKE_FILL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SelectedTreeItemEnum")
@XmlEnum
public enum SelectedTreeItemEnum {

    UNKNOWN,
    SLD,
    LAYER,
    STYLE,
    FEATURETYPESTYLE,
    RULE,
    POINT_SYMBOLIZER,
    LINE_SYMBOLIZER,
    POLYGON_SYMBOLIZER,
    TEXT_SYMBOLIZER,
    RASTER_SYMBOLIZER,
    POINT_FILL,
    POLYGON_FILL,
    STROKE,
    STROKE_FILL;

    public String value() {
        return name();
    }

    public static SelectedTreeItemEnum fromValue(String v) {
        return valueOf(v);
    }

}
