//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//

package com.sldeditor.common.xml.ui;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for SelectedTreeItemEnum.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p>
 *
 * <pre>
 * &lt;simpleType name="SelectedTreeItemEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNKNOWN"/&gt;
 *     &lt;enumeration value="SLD"/&gt;
 *     &lt;enumeration value="LAYER"/&gt;
 *     &lt;enumeration value="STYLE"/&gt;
 *     &lt;enumeration value="FEATURETYPESTYLE"/&gt;
 *     &lt;enumeration value="RULE"/&gt;
 *     &lt;enumeration value="POINT_SYMBOLIZER"/&gt;
 *     &lt;enumeration value="LINE_SYMBOLIZER"/&gt;
 *     &lt;enumeration value="POLYGON_SYMBOLIZER"/&gt;
 *     &lt;enumeration value="TEXT_SYMBOLIZER"/&gt;
 *     &lt;enumeration value="RASTER_SYMBOLIZER"/&gt;
 *     &lt;enumeration value="POINT_FILL"/&gt;
 *     &lt;enumeration value="POLYGON_FILL"/&gt;
 *     &lt;enumeration value="STROKE"/&gt;
 *     &lt;enumeration value="STROKE_FILL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "SelectedTreeItemEnum")
@XmlEnum
public enum SelectedTreeItemEnum {
    UNKNOWN,
    SLD,
    LAYER,
    STYLE,
    FEATURETYPESTYLE,
    RULE,
    POINT_SYMBOLIZER,
    LINE_SYMBOLIZER,
    POLYGON_SYMBOLIZER,
    TEXT_SYMBOLIZER,
    RASTER_SYMBOLIZER,
    POINT_FILL,
    POLYGON_FILL,
    STROKE,
    STROKE_FILL;

    public String value() {
        return name();
    }

    public static SelectedTreeItemEnum fromValue(String v) {
        return valueOf(v);
    }
}
