//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//

package com.sldeditor.common.xml.ui;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Configuration to compare a colour map entry values of a field
 *
 * <p>Java class for XMLColourMapEntries complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XMLColourMapEntries">
 *   &lt;complexContent>
 *     &lt;extension base="{}XMLFieldBase">
 *       &lt;sequence>
 *         &lt;element name="Entry" type="{}XMLColourMapEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "XMLColourMapEntries",
        propOrder = {"entry"})
public class XMLColourMapEntries extends XMLFieldBase {

    @XmlElement(name = "Entry")
    protected List<XMLColourMapEntry> entry;

    /**
     * Gets the value of the entry property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the entry property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getEntry().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link XMLColourMapEntry }
     */
    public List<XMLColourMapEntry> getEntry() {
        if (entry == null) {
            entry = new ArrayList<XMLColourMapEntry>();
        }
        return this.entry;
    }
}
