//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//

package com.sldeditor.common.xml.ui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Configuration to compare a colour map entry value of a field
 *
 * <p>Java class for XMLColourMapEntry complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XMLColourMapEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="colour" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="opacity" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="quantity" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLColourMapEntry")
public class XMLColourMapEntry {

    @XmlAttribute(required = true)
    protected String label;

    @XmlAttribute(required = true)
    protected String colour;

    @XmlAttribute(required = true)
    protected double opacity;

    @XmlAttribute(required = true)
    protected int quantity;

    /**
     * Gets the value of the label property.
     *
     * @return possible object is {@link String }
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value allowed object is {@link String }
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the colour property.
     *
     * @return possible object is {@link String }
     */
    public String getColour() {
        return colour;
    }

    /**
     * Sets the value of the colour property.
     *
     * @param value allowed object is {@link String }
     */
    public void setColour(String value) {
        this.colour = value;
    }

    /** Gets the value of the opacity property. */
    public double getOpacity() {
        return opacity;
    }

    /** Sets the value of the opacity property. */
    public void setOpacity(double value) {
        this.opacity = value;
    }

    /** Gets the value of the quantity property. */
    public int getQuantity() {
        return quantity;
    }

    /** Sets the value of the quantity property. */
    public void setQuantity(int value) {
        this.quantity = value;
    }
}
