//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//

package com.sldeditor.common.xml.ui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for XMLFieldConfigEnumValueGroup complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XMLFieldConfigEnumValueGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{}GroupIdEnum" />
 *       &lt;attribute name="enabled" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLFieldConfigEnumValueGroup")
public class XMLFieldConfigEnumValueGroup {

    @XmlAttribute(required = true)
    protected GroupIdEnum id;

    @XmlAttribute(required = true)
    protected boolean enabled;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link GroupIdEnum }
     */
    public GroupIdEnum getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link GroupIdEnum }
     */
    public void setId(GroupIdEnum value) {
        this.id = value;
    }

    /**
     * Gets the value of the enabled property. This getter has been renamed from isEnabled() to
     * getEnabled() by cxf-xjc-boolean plugin.
     */
    public boolean getEnabled() {
        return enabled;
    }

    /** Sets the value of the enabled property. */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }
}
