//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//

package com.sldeditor.common.xml.ui;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Configuration for a list of enumeration values to display in XMLFieldConfigEnum field
 *
 * <p>Java class for XMLFieldConfigEnumValueList complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XMLFieldConfigEnumValueList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Value" type="{}XMLFieldConfigEnumValue" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "XMLFieldConfigEnumValueList",
        propOrder = {"value"})
public class XMLFieldConfigEnumValueList {

    @XmlElement(name = "Value", required = true)
    protected List<XMLFieldConfigEnumValue> value;

    /**
     * Gets the value of the value property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the value property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getValue().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link XMLFieldConfigEnumValue }
     */
    public List<XMLFieldConfigEnumValue> getValue() {
        if (value == null) {
            value = new ArrayList<XMLFieldConfigEnumValue>();
        }
        return this.value;
    }
}
