//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//

package com.sldeditor.common.xml.ui;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Option field configuration
 *
 * <p>Java class for XMLOptionGroup complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XMLOptionGroup"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Group" type="{}XMLGroupConfig" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{}GroupIdEnum" /&gt;
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="showLabel" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "XMLOptionGroup",
        propOrder = {"group"})
public class XMLOptionGroup {

    @XmlElement(name = "Group")
    protected List<XMLGroupConfig> group;

    @XmlAttribute(name = "id", required = true)
    protected GroupIdEnum id;

    @XmlAttribute(name = "label")
    protected String label;

    @XmlAttribute(name = "showLabel")
    protected Boolean showLabel;

    /**
     * Gets the value of the group property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the group property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getGroup().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link XMLGroupConfig }
     */
    public List<XMLGroupConfig> getGroup() {
        if (group == null) {
            group = new ArrayList<XMLGroupConfig>();
        }
        return this.group;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link GroupIdEnum }
     */
    public GroupIdEnum getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link GroupIdEnum }
     */
    public void setId(GroupIdEnum value) {
        this.id = value;
    }

    /**
     * Gets the value of the label property.
     *
     * @return possible object is {@link String }
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     *
     * @param value allowed object is {@link String }
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the showLabel property. This getter has been renamed from isShowLabel() to
     * getShowLabel() by cxf-xjc-boolean plugin.
     *
     * @return possible object is {@link Boolean }
     */
    public boolean getShowLabel() {
        if (showLabel == null) {
            return false;
        } else {
            return showLabel;
        }
    }

    /**
     * Sets the value of the showLabel property.
     *
     * @param value allowed object is {@link Boolean }
     */
    public void setShowLabel(Boolean value) {
        this.showLabel = value;
    }
}
