//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.23 at 06:11:16 PM GMT 
//


package com.sldeditor.common.xml.ui;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Configuration for testing panels
 *             
 * 
 * <p>Java class for XMLPanelTest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XMLPanelTest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Setup" type="{}XMLSetup"/&gt;
 *         &lt;element name="FieldTests" type="{}XMLFieldTest" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLPanelTest", propOrder = {
    "setup",
    "fieldTests"
})
public class XMLPanelTest {

    @XmlElement(name = "Setup", required = true)
    protected XMLSetup setup;
    @XmlElement(name = "FieldTests")
    protected List<XMLFieldTest> fieldTests;

    /**
     * Gets the value of the setup property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSetup }
     *     
     */
    public XMLSetup getSetup() {
        return setup;
    }

    /**
     * Sets the value of the setup property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSetup }
     *     
     */
    public void setSetup(XMLSetup value) {
        this.setup = value;
    }

    /**
     * Gets the value of the fieldTests property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldTests property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldTests().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLFieldTest }
     * 
     * 
     */
    public List<XMLFieldTest> getFieldTests() {
        if (fieldTests == null) {
            fieldTests = new ArrayList<XMLFieldTest>();
        }
        return this.fieldTests;
    }

}
