//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//

package com.sldeditor.common.xml.ui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for XMLSetFieldLiteralBase complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XMLSetFieldLiteralBase">
 *   &lt;complexContent>
 *     &lt;extension base="{}XMLFieldBase">
 *       &lt;attribute name="ignoreCheck" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLSetFieldLiteralBase")
@XmlSeeAlso({
    XMLSetFieldLiteralIntEx.class,
    XMLSetFieldLiteralDoubleEx.class,
    XMLSetFieldLiteralBooleanEx.class,
    XMLSetFieldLiteralStringEx.class
})
public class XMLSetFieldLiteralBase extends XMLFieldBase {

    @XmlAttribute protected Boolean ignoreCheck;

    /**
     * Gets the value of the ignoreCheck property.
     *
     * @return possible object is {@link Boolean }
     */
    public boolean getIgnoreCheck() {
        if (ignoreCheck == null) {
            return false;
        } else {
            return ignoreCheck;
        }
    }

    /**
     * Sets the value of the ignoreCheck property.
     *
     * @param value allowed object is {@link Boolean }
     */
    public void setIgnoreCheck(Boolean value) {
        this.ignoreCheck = value;
    }
}
