//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//

package com.sldeditor.common.xml.ui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Configuration to enable/disable a group
 *
 * <p>Java class for XMLSetGroup complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XMLSetGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="groupId" use="required" type="{}GroupIdEnum" />
 *       &lt;attribute name="enable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLSetGroup")
public class XMLSetGroup {

    @XmlAttribute(required = true)
    protected GroupIdEnum groupId;

    @XmlAttribute(required = true)
    protected boolean enable;

    /**
     * Gets the value of the groupId property.
     *
     * @return possible object is {@link GroupIdEnum }
     */
    public GroupIdEnum getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     *
     * @param value allowed object is {@link GroupIdEnum }
     */
    public void setGroupId(GroupIdEnum value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the enable property. This getter has been renamed from isEnable() to
     * getEnable() by cxf-xjc-boolean plugin.
     */
    public boolean getEnable() {
        return enable;
    }

    /** Sets the value of the enable property. */
    public void setEnable(boolean value) {
        this.enable = value;
    }
}
