//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//


package com.sldeditor.common.xml.ui;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Configuration describe how to identify SLD attributes using XPATH 
 *             
 * 
 * <p>Java class for XMLTestSection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XMLTestSection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Field" type="{}XMLTestSectionField" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="prefix" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sldtype" use="required" type="{}SelectedTreeItemEnum" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLTestSection", propOrder = {
    "field"
})
public class XMLTestSection {

    @XmlElement(name = "Field")
    protected List<XMLTestSectionField> field;
    @XmlAttribute(required = true)
    protected String prefix;
    @XmlAttribute(required = true)
    protected SelectedTreeItemEnum sldtype;

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLTestSectionField }
     * 
     * 
     */
    public List<XMLTestSectionField> getField() {
        if (field == null) {
            field = new ArrayList<XMLTestSectionField>();
        }
        return this.field;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the sldtype property.
     * 
     * @return
     *     possible object is
     *     {@link SelectedTreeItemEnum }
     *     
     */
    public SelectedTreeItemEnum getSldtype() {
        return sldtype;
    }

    /**
     * Sets the value of the sldtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectedTreeItemEnum }
     *     
     */
    public void setSldtype(SelectedTreeItemEnum value) {
        this.sldtype = value;
    }

}
