//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: [TEXT REMOVED by maven-replacer-plugin]
//

package com.sldeditor.common.xml.ui;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Definition of 2 colour ramps
 *
 * <p>Java class for XMLTwoColourRampList complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="XMLTwoColourRampList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TwoColourRamp" type="{}XMLTwoColourRamp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "XMLTwoColourRampList",
        propOrder = {"twoColourRamp"})
public class XMLTwoColourRampList {

    @XmlElement(name = "TwoColourRamp")
    protected List<XMLTwoColourRamp> twoColourRamp;

    /**
     * Gets the value of the twoColourRamp property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the twoColourRamp property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getTwoColourRamp().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link XMLTwoColourRamp }
     */
    public List<XMLTwoColourRamp> getTwoColourRamp() {
        if (twoColourRamp == null) {
            twoColourRamp = new ArrayList<XMLTwoColourRamp>();
        }
        return this.twoColourRamp;
    }
}
